// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fXPdAnQjoGxiGfL42gFLODYfx9uioM4',
    appId: '1:586389757093:web:adfa816dd96375938e814c',
    messagingSenderId: '586389757093',
    projectId: 'to-do-list-66bf8',
    authDomain: 'to-do-list-66bf8.firebaseapp.com',
    storageBucket: 'to-do-list-66bf8.firebasestorage.app',
    measurementId: 'G-BP0E78TS54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevGxH1s4Yg7rQWj54qgkwV6jFdD6LqF4',
    appId: '1:586389757093:android:2fbbc195d35ce0f28e814c',
    messagingSenderId: '586389757093',
    projectId: 'to-do-list-66bf8',
    storageBucket: 'to-do-list-66bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOPIe7r5TXDU1a47W9gbXHTptyByBwHOw',
    appId: '1:586389757093:ios:0ade9dab15ea9e228e814c',
    messagingSenderId: '586389757093',
    projectId: 'to-do-list-66bf8',
    storageBucket: 'to-do-list-66bf8.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8fXPdAnQjoGxiGfL42gFLODYfx9uioM4',
    appId: '1:586389757093:web:6e8d229c294a8c288e814c',
    messagingSenderId: '586389757093',
    projectId: 'to-do-list-66bf8',
    authDomain: 'to-do-list-66bf8.firebaseapp.com',
    storageBucket: 'to-do-list-66bf8.firebasestorage.app',
    measurementId: 'G-GH32PNTDZC',
  );
}
